### PR TITLE
Added typescript.definition entry in package.json for tsd #10

### PR DESCRIPTION
**Pull request by cybrown**

### CODE REVIEW

**Comment by cybrown** [comment]
Added entry in package.json, I hope this will be usefull

**Comment by antonmoiseev** [comment]
@rbuckton are you accepting PRs in this repo? This PR looks tiny but very useful for TypeScript projects.

**Comment by rbuckton** [comment]
@antonmoiseev I need to clarify with Microsoft Legal as to whether contributors need to sign a CLA (http://cla.microsoft.com) for this repo.

**Comment by rbuckton** [comment]
We can add this for `tsd` support. Thanks!

**Comment by cybrown** [comment]
Thank you for the merge, but I hope it will be obsolete as soon as possible with the "typings" field !

**Pull request merged**
